[exec]
  allow = [
    '^gohugoio',
    '^python$',
    '^go$',
    '^npx$',
    '^postcss$',
    '^tailwindcss$'
  ]

[node.permissions]
  allowAddons = ["tailwindcss"]
  allowChildProcess = ["tailwindcss"]
  allowRead = [".", "..", "/"]
  allowWorker = ["tailwindcss"]