enableInlineShortcodes = false
allowContent = ['! ^text/html$']

[exec]
  allow = ['^(dart-)?sass$', '^go$', '^git$', '^node$', '^postcss$', '^tailwindcss$']

[node]
  [node.permissions]
    allowAddons = ["tailwindcss"]
    allowChildProcess = ["tailwindcss"]
    allowRead = [".", "..", "/"]
    allowWorker = ["tailwindcss"]